version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stockmoat_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: stockmoat
    ports:
      - "5432:5432"
    volumes:
      - stockmoat_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql

volumes:
  stockmoat_data:
